import type { AppData } from './types'

function monthDate(day: number): string {
  const now = new Date()
  const d = new Date(now.getFullYear(), now.getMonth(), Math.min(day, 28))
  return d.toISOString().split('T')[0]
}

const NOW = new Date().toISOString()

export const SEED_DATA: AppData = {
  clients: [
    {
      id: 'client-1',
      businessName: 'Maple Street Bakery',
      contactName: 'Sandra Chen',
      email: 'sandra@maplestreet.com',
      phone: '(555) 241-8830',
      businessType: 'Retail / Food Service',
      status: 'active',
      notes: 'Monthly reconciliation due by the 5th. Remind about quarterly sales tax.',
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'client-2',
      businessName: 'Rivera Plumbing LLC',
      contactName: 'Marco Rivera',
      email: 'marco@riveraplumbing.com',
      phone: '(555) 388-4421',
      businessType: 'Trades / Construction',
      status: 'active',
      notes: 'Quarterly estimated taxes — remind in March, June, Sept, Dec.',
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],
  categories: [
    { id: 'cat-inc-1', name: 'Service Revenue', type: 'income', active: true },
    { id: 'cat-inc-2', name: 'Product Sales', type: 'income', active: true },
    { id: 'cat-inc-3', name: 'Consulting Income', type: 'income', active: true },
    { id: 'cat-inc-4', name: 'Other Income', type: 'income', active: true },
    { id: 'cat-exp-1', name: 'Rent & Utilities', type: 'expense', active: true },
    { id: 'cat-exp-2', name: 'Payroll & Wages', type: 'expense', active: true },
    { id: 'cat-exp-3', name: 'Supplies & Materials', type: 'expense', active: true },
    { id: 'cat-exp-4', name: 'Marketing & Advertising', type: 'expense', active: true },
    { id: 'cat-exp-5', name: 'Insurance', type: 'expense', active: true },
    { id: 'cat-exp-6', name: 'Professional Services', type: 'expense', active: true },
    { id: 'cat-exp-7', name: 'Vehicle & Travel', type: 'expense', active: true },
    { id: 'cat-exp-8', name: 'Software & Subscriptions', type: 'expense', active: true },
    { id: 'cat-exp-9', name: 'Meals & Entertainment', type: 'expense', active: true },
    { id: 'cat-exp-10', name: 'Miscellaneous', type: 'expense', active: true },
  ],
  transactions: [
    {
      id: 'txn-1',
      clientId: 'client-1',
      date: monthDate(1),
      type: 'income',
      payee: 'Catering Event — City Hall',
      categoryId: 'cat-inc-1',
      account: 'Checking',
      amount: 1850.0,
      memo: 'Corporate lunch order',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-2',
      clientId: 'client-1',
      date: monthDate(3),
      type: 'expense',
      payee: 'Sysco Foods',
      categoryId: 'cat-exp-3',
      account: 'Checking',
      amount: 640.5,
      memo: 'Weekly ingredient order',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-3',
      clientId: 'client-1',
      date: monthDate(5),
      type: 'expense',
      payee: 'Metro Property Group',
      categoryId: 'cat-exp-1',
      account: 'Checking',
      amount: 2200.0,
      memo: 'Monthly rent',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-4',
      clientId: 'client-1',
      date: monthDate(8),
      type: 'income',
      payee: 'Retail Sales — Week 2',
      categoryId: 'cat-inc-2',
      account: 'Checking',
      amount: 3120.75,
      memo: '',
      cleared: false,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-5',
      clientId: 'client-1',
      date: monthDate(10),
      type: 'expense',
      payee: 'Google Workspace',
      categoryId: 'cat-exp-8',
      account: 'Visa Business',
      amount: 18.0,
      memo: 'Monthly subscription',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-6',
      clientId: 'client-2',
      date: monthDate(2),
      type: 'income',
      payee: 'Hartley Residence',
      categoryId: 'cat-inc-1',
      account: 'Checking',
      amount: 875.0,
      memo: 'Emergency pipe repair',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-7',
      clientId: 'client-2',
      date: monthDate(4),
      type: 'income',
      payee: 'Greenview Apartments',
      categoryId: 'cat-inc-1',
      account: 'Checking',
      amount: 2400.0,
      memo: 'Monthly maintenance contract',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-8',
      clientId: 'client-2',
      date: monthDate(6),
      type: 'expense',
      payee: 'Home Depot',
      categoryId: 'cat-exp-3',
      account: 'Checking',
      amount: 312.4,
      memo: 'Pipe fittings and supplies',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-9',
      clientId: 'client-2',
      date: monthDate(7),
      type: 'expense',
      payee: 'Allstate Insurance',
      categoryId: 'cat-exp-5',
      account: 'Checking',
      amount: 420.0,
      memo: 'Commercial liability — monthly',
      cleared: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'txn-10',
      clientId: 'client-2',
      date: monthDate(9),
      type: 'expense',
      payee: 'Fuel — Company Van',
      categoryId: null,
      account: 'Visa Business',
      amount: 148.6,
      memo: '',
      cleared: false,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],
  selectedClientId: 'client-1',
}
